seed: 42
model_name: bert-base-uncased
max_length: 256
train_batch_size: 8
eval_batch_size: 16
num_train_epochs: 3
learning_rate: 2e-5
output_dir: ./models/exp1
logging_dir: ./logs
save_steps: 1000
eval_steps: 200
dataset: imdb
train_file: data/processed/imdb_train.csv
val_file: data/processed/imdb_val.csv
test_file: data/processed/imdb_test.csv
wandb:
  project: "imdb-sentiment"
  run_name: "exp1"
